/*
 * Copyright 2026 Franz Schöning
 * Project: https://github.com/SwarmCoder/swarmcoder
 * Author: Franz Schöning - Principal Enterprise Architect (https://www.franzschoning.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.swarmcoder.console;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.XWPFDocument;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.util.Locale;

/**
 * Turns an uploaded file into plain text for the BRD intake pipeline.
 *
 * <p>This is the {@code extractor} stage of the document intake pipeline described in
 * {@code docs/REQUIREMENTS_AND_BACKLOG_DESIGN.md} §4.1:
 *
 * <pre>
 * upload (drop / picker / paste)
 *    -&gt; size + type guard
 *    -&gt; EXTRACTOR            &lt;-- this class
 *    -&gt; SourceDocument persisted (text + sha256 + provenance)
 *    -&gt; BRD author agent: extract DRAFT requirements, each with a SourceRef
 * </pre>
 *
 * <p>The extracted text is what the BRD authoring agent actually reads, so the output is
 * normalised (BOM stripped, CRLF collapsed to LF, runs of blank lines squeezed, trimmed) to keep
 * the agent prompt clean — PDF text extraction in particular is noisy.
 *
 * <h2>This class never throws and never talks to the network</h2>
 *
 * <p>Every failure path — a corrupt PDF, a truncated .docx, an unsupported extension — comes back
 * as an {@link Extracted} with a non-null {@link Extracted#error()}. A malformed upload must never
 * take the console server down.
 *
 * <p>Images are <em>not</em> extracted here. An image upload returns an {@link Extracted} with
 * {@code extractedBy = "vision"} and null text and null error, which is a signal to the caller that
 * it must run the configured {@code roles.vision} model over the bytes. Making that call requires a
 * network round trip and configuration this class deliberately knows nothing about.
 *
 * <p><b>Vision output is a model's reading of an image, not the document itself.</b> Anything
 * produced downstream under {@code extractedBy = "vision"} is a paraphrase generated by a language
 * model that looked at a picture: it can hallucinate, drop table cells, misread handwriting and
 * invent plausible-sounding requirements. It must stay labelled as such all the way through to the
 * operator, who is the one deciding whether a DRAFT requirement becomes ACTIVE. Text coming back as
 * {@code "passthrough"}, {@code "pdfbox"} or {@code "poi"} is, by contrast, a faithful decoding of
 * bytes the user actually uploaded.
 */
public final class DocumentExtractor {

    /** Upper bound on extracted text; anything longer is truncated with a marker. */
    public static final int MAX_EXTRACTED_CHARS = 10_000_000;

    /** Marker used for the passthrough (already-text) path. */
    public static final String BY_PASSTHROUGH = "passthrough";
    /** Marker used for PDF text extracted with PDFBox. */
    public static final String BY_PDFBOX = "pdfbox";
    /** Marker used for OOXML Word documents extracted with Apache POI. */
    public static final String BY_POI = "poi";
    /** Marker meaning "the caller must run the vision model over these bytes". */
    public static final String BY_VISION = "vision";

    /** U+FEFF — a UTF-8 BOM decodes to this and would otherwise poison the first token. */
    private static final char BOM = '﻿';

    private static final String SUPPORTED =
            "text (.md, .markdown, .txt, .adoc, .rst, .csv), .pdf, .docx, "
            + "images (.png, .jpg, .jpeg, .webp, .gif)";

    private DocumentExtractor() {
    }

    /**
     * The result of an extraction attempt.
     *
     * <p>Exactly one of three shapes:
     * <ul>
     *   <li><b>success</b> — {@code text} non-null, {@code error} null, {@code extractedBy} one of
     *       {@code passthrough} / {@code pdfbox} / {@code poi};</li>
     *   <li><b>needs vision</b> — {@code text} null, {@code error} null,
     *       {@code extractedBy = "vision"}; see {@link #needsVision(Extracted)};</li>
     *   <li><b>failure</b> — {@code error} non-null, and {@code text} must not be used.</li>
     * </ul>
     *
     * @param text        the extracted plain text, or null when there is none (yet)
     * @param extractedBy how the text was obtained; persisted onto the {@code SourceDocument} so
     *                    the operator can tell a faithful decode from a model's reading
     * @param error       a short human-readable reason; non-null means extraction failed and
     *                    {@code text} is unusable
     */
    public record Extracted(String text, String extractedBy, String error) {

        /** @return true when extraction failed and {@link #text()} must not be used. */
        public boolean failed() {
            return error != null;
        }
    }

    /**
     * Extracts plain text from an uploaded document. Never throws.
     *
     * <p>Dispatch is on the filename extension first and falls back to {@code mediaType} when the
     * filename carries no usable extension — browsers are far more reliable about the filename than
     * about the media type, and a {@code .md} arriving as {@code application/octet-stream} is
     * common.
     *
     * @param filename  the original filename, may be null
     * @param mediaType the declared media type, may be null
     * @param bytes     the raw uploaded bytes
     * @return an {@link Extracted}; check {@link Extracted#error()} and
     *         {@link #needsVision(Extracted)} before using {@link Extracted#text()}
     */
    public static Extracted extract(String filename, String mediaType, byte[] bytes) {
        if (bytes == null) {
            return error("no bytes were supplied");
        }
        String ext = extensionOf(filename);
        String type = mediaType == null ? "" : mediaType.trim().toLowerCase(Locale.ROOT);

        // 1. Extension wins.
        Extracted byExtension = dispatchExtension(ext, bytes);
        if (byExtension != null) {
            return byExtension;
        }

        // 2. An extension we do not recognise is a hard no — don't let a generic "text/plain"
        //    media type smuggle a .exe through as text.
        if (!ext.isEmpty()) {
            return unsupported(ext);
        }

        // 3. No usable extension: fall back to the declared media type.
        if (type.startsWith("image/")) {
            return vision();
        }
        if (type.startsWith("text/")) {
            return passthrough(bytes);
        }
        if (type.equals("application/pdf")) {
            return pdf(bytes);
        }
        if (type.equals("application/vnd.openxmlformats-officedocument.wordprocessingml.document")) {
            return docx(bytes);
        }
        if (type.equals("application/msword")) {
            return legacyDoc();
        }
        return error("cannot determine the document type of '" + safeName(filename)
                + "' (media type '" + (mediaType == null ? "none" : mediaType)
                + "'); supported: " + SUPPORTED);
    }

    /**
     * @return true when this result is the "hand these bytes to the vision model" signal rather
     *         than text or an error. The caller is responsible for the model call.
     */
    public static boolean needsVision(Extracted e) {
        return e != null && BY_VISION.equals(e.extractedBy()) && e.text() == null && e.error() == null;
    }

    // --- dispatch -------------------------------------------------------------------------

    /** @return the result for a recognised extension, or null when the extension tells us nothing. */
    private static Extracted dispatchExtension(String ext, byte[] bytes) {
        return switch (ext) {
            case "md", "markdown", "txt", "adoc", "rst", "csv" -> passthrough(bytes);
            case "pdf" -> pdf(bytes);
            case "docx" -> docx(bytes);
            case "doc" -> legacyDoc();
            case "png", "jpg", "jpeg", "webp", "gif" -> vision();
            default -> null;
        };
    }

    private static Extracted passthrough(byte[] bytes) {
        try {
            return ok(new String(bytes, StandardCharsets.UTF_8), BY_PASSTHROUGH);
        } catch (RuntimeException | OutOfMemoryError e) {
            return error("could not decode the file as UTF-8 text: " + reason(e));
        }
    }

    private static Extracted pdf(byte[] bytes) {
        try (PDDocument doc = Loader.loadPDF(bytes)) {
            if (doc.isEncrypted()) {
                return error("the PDF is encrypted; upload an unprotected copy or paste the text");
            }
            PDFTextStripper stripper = new PDFTextStripper();
            stripper.setSortByPosition(true);
            String text = stripper.getText(doc);
            if (text == null || text.isBlank()) {
                return error("the PDF contains no extractable text — it is probably a scan; "
                        + "upload it as an image so the vision model can read it, or paste the text");
            }
            return ok(text, BY_PDFBOX);
        } catch (Exception | OutOfMemoryError | StackOverflowError e) {
            return error("could not read the PDF: " + reason(e));
        }
    }

    private static Extracted docx(byte[] bytes) {
        try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(bytes));
             XWPFWordExtractor extractor = new XWPFWordExtractor(doc)) {
            String text = extractor.getText();
            if (text == null) {
                return error("could not read the .docx: the extractor produced no text");
            }
            return ok(text, BY_POI);
        } catch (Exception | OutOfMemoryError | StackOverflowError e) {
            return error("could not read the .docx: " + reason(e));
        }
    }

    private static Extracted legacyDoc() {
        return error("legacy binary Word (.doc) is not supported; "
                + "re-save the document as .docx, or upload it as plain text or PDF");
    }

    private static Extracted vision() {
        return new Extracted(null, BY_VISION, null);
    }

    private static Extracted unsupported(String ext) {
        return error("unsupported file type '." + ext + "'; supported: " + SUPPORTED);
    }

    private static Extracted ok(String raw, String extractedBy) {
        return new Extracted(cap(normalise(raw)), extractedBy, null);
    }

    private static Extracted error(String message) {
        return new Extracted(null, null, message);
    }

    // --- text hygiene ---------------------------------------------------------------------

    /**
     * Strips a UTF-8 BOM, normalises CRLF and lone CR to LF, collapses runs of three or more
     * blank lines down to two, and trims. PDF extraction in particular emits a lot of vertical
     * whitespace that would otherwise burn agent context for nothing.
     */
    static String normalise(String raw) {
        if (raw == null || raw.isEmpty()) {
            return "";
        }
        String s = raw;
        if (s.charAt(0) == BOM) {
            s = s.substring(1);
        }
        s = s.replace("\r\n", "\n").replace('\r', '\n');
        // 3+ newlines (i.e. 2+ blank lines) -> exactly one blank line.
        s = s.replaceAll("\n{3,}", "\n\n");
        // Trailing spaces on a line are pure noise in extracted text.
        s = s.replaceAll("[ \t]+\n", "\n");
        return s.strip();
    }

    /** Truncates to {@link #MAX_EXTRACTED_CHARS}, marking the cut so nothing looks complete when it isn't. */
    static String cap(String s) {
        if (s == null || s.length() <= MAX_EXTRACTED_CHARS) {
            return s;
        }
        int dropped = s.length() - MAX_EXTRACTED_CHARS;
        return s.substring(0, MAX_EXTRACTED_CHARS) + "\n\n[truncated: " + dropped + " more characters]";
    }

    // --- helpers --------------------------------------------------------------------------

    /** @return the lowercase extension without the dot, or "" when there is none. */
    static String extensionOf(String filename) {
        if (filename == null) {
            return "";
        }
        String name = filename.trim();
        // Tolerate a path being handed in instead of a bare filename.
        int slash = Math.max(name.lastIndexOf('/'), name.lastIndexOf('\\'));
        if (slash >= 0) {
            name = name.substring(slash + 1);
        }
        int dot = name.lastIndexOf('.');
        if (dot < 0 || dot == name.length() - 1) {
            return "";
        }
        return name.substring(dot + 1).toLowerCase(Locale.ROOT);
    }

    private static String safeName(String filename) {
        return filename == null || filename.isBlank() ? "(unnamed)" : filename.trim();
    }

    private static String reason(Throwable e) {
        String m = e.getMessage();
        String cls = e.getClass().getSimpleName();
        if (m == null || m.isBlank()) {
            return cls;
        }
        String flat = m.replaceAll("\\s+", " ").trim();
        if (flat.length() > 200) {
            flat = flat.substring(0, 200) + "...";
        }
        return cls + ": " + flat;
    }
}
